openapi: 3.0.2
info:
    title: TARgv23GameApi
    version: 1.0.0
    description: see all da gaem
paths:
    /games:
        get:
            tags:
                - games
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                            examples:
                                List of games:
                                    value:
                                        - Wither 3
                                        - CyberPunk 2077
                    description: Returns a list of Games
            summary: Get a list of all games
            description: Returns a list of all games in the api
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Game'
                        examples:
                            Example of a game:
                                value:
                                    name: Super Mario Bros.
                                    releaseEU: '1985'
                                    description: italian spaghetti gaem
                                    reviewscore: '78'
                required: true
            tags:
                - games
            responses:
                '201':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Game'
                            examples:
                                Example of a game:
                                    value:
                                        id: 5
                                        name: Super Mario Bros.
                                        releaseEU: '1985'
                                        description: italian spaghetti gaem
                                        reviewscore: '78'
                    description: Return 201 to user when creation of new Game is successful
            summary: Add a new Game
            description: 'Returns the created Game to the user, if creation is successful'
    '/games/{id}':
        get:
            tags:
                - games
            parameters:
                -
                    examples:
                        example id:
                            value:
                                - 8
                    name: id
                    schema:
                        type: integer
                    in: path
                    required: true
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                            examples:
                                Game with details:
                                    value:
                                        id: 2
                                        name: Sonic the Hedgehog
                                        releaseEU: '1991'
                                        description: Speedy blue platformer
                                        reviewscore: 77
                    description: Returns details of a game by its id
                '400':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                Missing parameters:
                                    value:
                                        Error: invalid game id
                    description: ID was missing
                '404':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                Missing game:
                                    value:
                                        Error: Game not found
                    description: Game was not found in array of games
            operationId: id
            summary: Get full details of a Game
            description: Return full details of a given Game based on the id
        put:
            requestBody:
                content:
                    application/json:
                        schema:
                            type: array
                            items:
                                type: string
                        examples:
                            Example of modified game:
                                value:
                                    id: 2
                                    name: originalname
                                    releaseEU: '2077'
                                    description: küberpunk sshit
                                    reviewscore: '3'
                required: true
            tags:
                - games
            parameters:
                -
                    examples:
                        Id of game to be modified:
                            value: '1'
                    name: id
                    description: id of game
                    schema:
                        type: integer
                    in: path
                    required: true
            responses:
                '201':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Game'
                            examples:
                                Example of a modified game:
                                    value:
                                        id: 2
                                        name: modifiedname
                                        releaseEU: '2077'
                                        description: küberpunk sshit
                                        reviewscore: '3'
                    description: A game has been successfully modified
                '400':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                Missing parameters:
                                    value:
                                        -
                                            error: one or all params missing
                    description: parameter was not found
                '404':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                Game /w+ was not found:
                                    value:
                                        Error: Game not found
                    description: Game with this id was not found
            operationId: id
            summary: modify existing game
            description: Modify a single game in the app
        delete:
            tags:
                - games
            parameters:
                -
                    examples:
                        Id of Game to be deleted:
                            value: '1'
                    name: id
                    description: id of Game to be deleted
                    schema:
                        type: integer
                    in: path
                    required: true
            responses:
                '204':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                example of deleted game:
                                    value:
                                        -
                                            error: no content
                    description: Return status 204 to the user if deletion of a Game has been successful
                '404':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                Game /w+ was not found:
                                    value:
                                        -
                                            error: game was not found
                    description: 'Return status code 404 to the user, if game with this id does not exist'
            operationId: id
            description: Delete a game with this id
components:
    schemas:
        error:
            description: "{\r\n  \"Error\": \"error message\"\r\n}"
            type: object
        Game:
            title: Root Type for Game
            description: Data of Game datatype
            type: object
            properties:
                name:
                    type: string
                releaseEU:
                    type: string
                description:
                    type: string
                reviewscore:
                    type: string
            example:
                name: Super Mario Bros.
                releaseEU: '1985'
                description: italian spaghetti gaem
                reviewscore: '78'
